id: xccdf_org.ssgproject.content_rule_configure_auditd_num_logs
severity: medium
title: Configure auditd Number of Logs Retained
description: |
  Determine how many log files `auditd` should retain when it rotates
  logs. Edit the file `/etc/audit/auditd.conf`. Add or modify the
  following line, substituting *NUMLOGS* with the correct value:

      num_logs = NUMLOGS

  Set the value to 5 for general-purpose systems. Note that values less
  than 2 result in no log rotation.
rationale: |
  The total storage for audit log files must be large enough to retain log
  information over the period required. This is a function of the maximum
  log file size and the number of logs retained.
references:
- href: http://csrc.nist.gov/publications/nistpubs/800-53-Rev3/sp800-53-rev3-final.pdf
  value: AU-1(b)
- href: http://csrc.nist.gov/publications/nistpubs/800-53-Rev3/sp800-53-rev3-final.pdf
  value: AU-11
- href: http://csrc.nist.gov/publications/nistpubs/800-53-Rev3/sp800-53-rev3-final.pdf
  value: IR-5
- href: test_attestation
  dc:contributor: DS
  dc:date: '20121024'
crosswalk:
- system: http://cce.mitre.org
  value: CCE-27522-2
tests:
- type: ind:textfilecontent54_test
  check: all
  comment: 'admin space left action '
  version: '1'
  object:
    version: '2'
    ind:filepath: /etc/audit/auditd.conf
    ind:pattern:
      operation: pattern match
      value: ^[ ]*num_logs[ ]+=[ ]+(\d+)[ ]*$
    ind:instance: 1
  state:
    version: '1'
    ind:subexpression:
      operation: greater than or equal
      var_ref: oval:ssg:var:2244
