id: xccdf_org.ssgproject.content_rule_configure_logwatch_hostlimit
severity: low
title: Configure Logwatch HostLimit Line
description: |
  On a central logserver, you want Logwatch to summarize all syslog
  entries, including those which did not originate on the logserver
  itself. The `HostLimit` setting tells Logwatch to report on all hosts,
  not just the one on which it is running.

       HostLimit = no
rationale: ~
references: []
crosswalk:
- system: http://cce.mitre.org
  value: CCE-27197-3
operator: AND
tests:
- type: ind:textfilecontent54_test
  check: all
  check_existence: all_exist
  comment: Test HostLimit
  version: '1'
  object:
    version: '1'
    ind:path: /etc/logwatch/conf
    ind:filename: logwatch.conf
    ind:pattern:
      operation: pattern match
      value: ^[\s]HostLimit[\s]*=[\s]*no[\s]*$
    ind:instance: 1
